<?php 
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
	'key' => 'group_575a26a2487d6',
	'title' => 'Card - Element',
	'fields' => array (
		array (
			'key' => 'field_577dc033f3d8b',
			'label' => 'Content',
			'name' => 'options_copy_copy',
			'type' => 'accordion',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'icon_class' => 'dashicons-text',
		),
		array (
			'key' => 'field_5760fe6182257',
			'label' => 'No Field Selected',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_575a2d9263690',
						'operator' => '==',
						'value' => 'h6',
					),
					array (
						'field' => 'field_575a2d9263690',
						'operator' => '==',
						'value' => 'h1',
					),
					array (
						'field' => 'field_575a2d9263690',
						'operator' => '==',
						'value' => 'p',
					),
					array (
						'field' => 'field_575a2d9263690',
						'operator' => '==',
						'value' => 'Button',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'No field selected for this tab',
			'new_lines' => '',
			'esc_html' => 0,
		),
		array (
			'key' => 'field_575a2d0d63688',
			'label' => 'Title',
			'name' => 'title',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_575a2d9263690',
						'operator' => '!=',
						'value' => 'h1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_575a2cf963687',
			'label' => 'Subtitle',
			'name' => 'subtitle',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_575a2d9263690',
						'operator' => '!=',
						'value' => 'h6',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_575a2d1963689',
			'label' => 'Content',
			'name' => 'content',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_575a2d9263690',
						'operator' => '!=',
						'value' => 'p',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
		),
		array (
			'key' => 'field_575a2d2b6368a',
			'label' => 'Button',
			'name' => 'button',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_575a2d9263690',
						'operator' => '!=',
						'value' => 'Button',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => '',
			'max' => '',
			'layout' => 'block',
			'button_label' => 'Add Button',
			'sub_fields' => array (
				array (
					'key' => 'field_575a2d336368b',
					'label' => 'Text',
					'name' => 'text',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_575a2d3e6368c',
					'label' => 'Link',
					'name' => 'link',
					'type' => 'page_link',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => array (
					),
					'taxonomy' => array (
					),
					'allow_null' => 0,
					'multiple' => 0,
				),
			),
		),
		array (
			'key' => 'field_575a2d9263690',
			'label' => 'Remove Elements',
			'name' => 'remove_elements',
			'type' => 'checkbox',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'h6' => 'Subtitle',
				'h1' => 'Title',
				'p' => 'Content',
				'Button' => 'Button',
			),
			'default_value' => array (
			),
			'layout' => 'horizontal',
			'toggle' => 0,
		),
		array (
			'key' => 'field_577dbfe606479',
			'label' => 'Display Options',
			'name' => 'options',
			'type' => 'accordion',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'icon_class' => 'dashicons-admin-settings',
		),
		array (
			'key' => 'field_576c78ae19688',
			'label' => 'Styles',
			'name' => 'class',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'default' => 'Default',
				'style1' => 'Style 1',
				'style2' => 'Style 2',
				'style3' => 'Style 3',
			),
			'default_value' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'disabled' => 0,
			'readonly' => 0,
		),
		array (
			'key' => 'field_577dc0030647a',
			'label' => 'Image',
			'name' => 'options_copy',
			'type' => 'accordion',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'icon_class' => 'dashicons-format-image',
		),
		array (
			'key' => 'field_575a2d686368e',
			'label' => 'Image',
			'name' => 'image',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_575a2d9263690',
						'operator' => '!=',
						'value' => 'img',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'special',
				'operator' => '==',
				'value' => 'nowhere',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_5768cdd1d2a96',
	'title' => 'Card with side image - Element',
	'fields' => array (
		array (
			'key' => 'field_577ddd5623de2',
			'label' => 'Content',
			'name' => 'content',
			'type' => 'accordion',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'icon_class' => 'dashicons-text',
		),
		array (
			'key' => 'field_5768cdd1de40b',
			'label' => 'No Field Selected',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_5768cdd1de8cd',
						'operator' => '==',
						'value' => 'h6',
					),
					array (
						'field' => 'field_5768cdd1de8cd',
						'operator' => '==',
						'value' => 'h1',
					),
					array (
						'field' => 'field_5768cdd1de8cd',
						'operator' => '==',
						'value' => 'p',
					),
					array (
						'field' => 'field_5768cdd1de8cd',
						'operator' => '==',
						'value' => 'Button',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'No field selected for this tab',
			'new_lines' => '',
			'esc_html' => 0,
		),
		array (
			'key' => 'field_5768cdd1de50e',
			'label' => 'Title',
			'name' => 'title',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_5768cdd1de8cd',
						'operator' => '!=',
						'value' => 'h1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_5768cdd1de48d',
			'label' => 'Subtitle',
			'name' => 'subtitle',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_5768cdd1de8cd',
						'operator' => '!=',
						'value' => 'h6',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_5768cdd1de58e',
			'label' => 'Content',
			'name' => 'content',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_5768cdd1de8cd',
						'operator' => '!=',
						'value' => 'p',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
		),
		array (
			'key' => 'field_5768cdd1de623',
			'label' => 'Button',
			'name' => 'button',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_5768cdd1de8cd',
						'operator' => '!=',
						'value' => 'Button',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => '',
			'max' => '',
			'layout' => 'block',
			'button_label' => 'Add Button',
			'sub_fields' => array (
				array (
					'key' => 'field_5768cdd2130b1',
					'label' => 'Text',
					'name' => 'text',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_5768cdd213132',
					'label' => 'Link',
					'name' => 'link',
					'type' => 'page_link',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => array (
					),
					'taxonomy' => array (
					),
					'allow_null' => 0,
					'multiple' => 0,
				),
			),
		),
		array (
			'key' => 'field_5768cdd1de8cd',
			'label' => 'Remove Elements',
			'name' => 'remove_elements',
			'type' => 'checkbox',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'h6' => 'Subtitle',
				'h1' => 'Title',
				'p' => 'Content',
				'Button' => 'Button',
			),
			'default_value' => array (
			),
			'layout' => 'horizontal',
			'toggle' => 0,
		),
		array (
			'key' => 'field_577ddd8923de3',
			'label' => 'Image',
			'name' => 'image',
			'type' => 'accordion',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'icon_class' => 'dashicons-format-image',
		),
		array (
			'key' => 'field_5768ce885e24e',
			'label' => 'Image Position',
			'name' => 'image_position',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'Right Side' => 'Right Side',
				'Left Side' => 'Left Side',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => 'Right Side',
			'layout' => 'horizontal',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'special',
				'operator' => '==',
				'value' => 'nowhere',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_575a30065a430-2',
	'title' => 'Form - Element',
	'fields' => array (
		array (
			'key' => 'field_577ca4c92bc11',
			'label' => 'Text introduction',
			'name' => 'form_intro',
			'type' => 'accordion',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'icon_class' => 'dashicons-text',
		),
		array (
			'key' => 'field_577dc53882a6d',
			'label' => 'No Fields Selected',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_575a300676afc',
						'operator' => '==',
						'value' => 'h6',
					),
					array (
						'field' => 'field_575a300676afc',
						'operator' => '==',
						'value' => 'h1',
					),
					array (
						'field' => 'field_575a300676afc',
						'operator' => '==',
						'value' => 'p',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'No field selected for this tab',
			'new_lines' => '',
			'esc_html' => 0,
		),
		array (
			'key' => 'field_575a300676862',
			'label' => 'Title',
			'name' => 'title',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_575a300676afc',
						'operator' => '!=',
						'value' => 'h1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_575a3006767f5',
			'label' => 'Subtitle',
			'name' => 'subtitle',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_575a300676afc',
						'operator' => '!=',
						'value' => 'h6',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_575a30d55f4d3',
			'label' => 'Content',
			'name' => 'content',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_575a300676afc',
						'operator' => '!=',
						'value' => 'p',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
		),
		array (
			'key' => 'field_575a300676afc',
			'label' => 'Remove Elements',
			'name' => 'remove_elements',
			'type' => 'checkbox',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'h6' => 'Subtitle',
				'h1' => 'Title',
				'p' => 'Content',
			),
			'default_value' => array (
			),
			'layout' => 'horizontal',
			'toggle' => 0,
		),
		array (
			'key' => 'field_577caad26c9ce',
			'label' => 'Form Options',
			'name' => '_copy',
			'type' => 'accordion',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'icon_class' => 'dashicons-email-alt',
		),
		array (
			'key' => 'field_575a30a95f4d1',
			'label' => 'Form',
			'name' => 'form',
			'type' => 'gravity_forms_field',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'allow_null' => 0,
			'allow_multiple' => 0,
		),
		array (
			'key' => 'field_5768a1de80136',
			'label' => 'Classes',
			'name' => 'class',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'special',
				'operator' => '==',
				'value' => 'nowhere',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_57578ce8e8b7b',
	'title' => 'Homepage Heading',
	'fields' => array (
		array (
			'key' => 'field_57578de1651d5',
			'label' => 'Slides',
			'name' => 'slides',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 1,
			'max' => '',
			'layout' => 'block',
			'button_label' => 'Add Slide',
			'sub_fields' => array (
				array (
					'key' => 'field_57639b9657c14',
					'label' => 'Card',
					'name' => 'card',
					'type' => 'reusable_field_group_field',
					'instructions' => '',
					'required' => '',
					'conditional_logic' => '',
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'group_key' => 'group_575a26a2487d6',
					'name_prefix' => 0,
					'key_prefix' => 1,
					'label_prefix' => 0,
				),
				array (
					'key' => 'field_5768cfc96b2e2',
					'label' => 'Background',
					'name' => 'background',
					'type' => 'image',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => 50,
						'class' => '',
						'id' => '',
					),
					'return_format' => 'url',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
			),
		),
		array (
			'key' => 'field_57578e7c651d8',
			'label' => 'Id',
			'name' => 'id',
			'type' => 'text',
			'instructions' => '',
			'required' => '',
			'conditional_logic' => '',
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '#',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
			array (
				'param' => 'page_type',
				'operator' => '==',
				'value' => 'front_page',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_575a379a3e69e',
	'title' => 'Image - Element',
	'fields' => array (
		array (
			'key' => 'field_575a37bdff72d',
			'label' => 'Image',
			'name' => 'image',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'side',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_575a390f78a8b',
	'title' => 'Image Grid - Element',
	'fields' => array (
		array (
			'key' => 'field_577dde0a0a268',
			'label' => 'List Items',
			'name' => 'list_items',
			'type' => 'accordion',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'icon_class' => 'dashicons-list-view',
		),
		array (
			'key' => 'field_575a3a9085b11',
			'label' => 'Image List',
			'name' => 'image_list',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => '',
			'max' => '',
			'layout' => 'row',
			'button_label' => 'Add image',
			'sub_fields' => array (
				array (
					'key' => 'field_575a3b2185b12',
					'label' => 'Image',
					'name' => 'image',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => 50,
						'class' => '',
						'id' => '',
					),
					'return_format' => 'url',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array (
					'key' => 'field_575a3b3285b13',
					'label' => 'Description',
					'name' => 'description',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
			),
		),
		array (
			'key' => 'field_577dde2d3346b',
			'label' => 'Display Options',
			'name' => 'list_items_copy',
			'type' => 'accordion',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'icon_class' => 'dashicons-admin-generic',
		),
		array (
			'key' => 'field_575a3c1b2378b',
			'label' => 'Column Number',
			'name' => 'column_number',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				12 => '1 column',
				6 => '2 column',
				4 => '3 column',
				3 => '4 column',
			),
			'default_value' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'disabled' => 0,
			'readonly' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'special',
				'operator' => '==',
				'value' => 'nowhere',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_575a31819691c',
	'title' => 'List - Element',
	'fields' => array (
		array (
			'key' => 'field_577de4440fd6b',
			'label' => 'Text Introduction',
			'name' => 'text_introduction',
			'type' => 'accordion',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'icon_class' => 'dashicons-text',
		),
		array (
			'key' => 'field_575a3181b5125',
			'label' => 'Title',
			'name' => 'title',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_575a3181b53c8',
						'operator' => '!=',
						'value' => 'h1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_575a3181b50b5',
			'label' => 'Subtitle',
			'name' => 'subtitle',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_575a3181b53c8',
						'operator' => '!=',
						'value' => 'h6',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_575a3181b5194',
			'label' => 'Content',
			'name' => 'content',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_575a3181b53c8',
						'operator' => '!=',
						'value' => 'p',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 0,
		),
		array (
			'key' => 'field_575a3181b53c8',
			'label' => 'Remove Elements',
			'name' => 'remove_elements',
			'type' => 'checkbox',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'h6' => 'Subtitle',
				'h1' => 'Title',
				'p' => 'Content',
			),
			'default_value' => array (
				0 => 'h6',
				1 => 'p',
			),
			'layout' => 'horizontal',
			'toggle' => 0,
		),
		array (
			'key' => 'field_577de46f0fd6c',
			'label' => 'List',
			'name' => 'text_introduction_copy',
			'type' => 'accordion',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'icon_class' => 'dashicons-list-view',
		),
		array (
			'key' => 'field_575a31e3d7f31',
			'label' => 'List',
			'name' => 'list',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => '',
			'max' => '',
			'layout' => 'block',
			'button_label' => 'Add Item',
			'sub_fields' => array (
				array (
					'key' => 'field_575a3483e26c8',
					'label' => 'Content',
					'name' => 'content',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => '',
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 1,
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'special',
				'operator' => '==',
				'value' => 'nowhere',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_5784862119b97',
	'title' => 'Media - Element',
	'fields' => array (
		array (
			'key' => 'field_57848628701ab',
			'label' => 'Embed',
			'name' => 'embed',
			'type' => 'oembed',
			'instructions' => 'List of supported embed content here https://codex.wordpress.org/Embeds#Okay.2C_So_What_Sites_Can_I_Embed_From.3F
',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'width' => '',
			'height' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'special',
				'operator' => '==',
				'value' => 'nowhere',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_574f919df35f8',
	'title' => 'Option Page - Site Details',
	'fields' => array (
		array (
			'key' => 'field_574f91ae7a28f',
			'label' => 'Branding',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_574f91f97a290',
			'label' => 'Logo',
			'name' => 'logo',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_574f965baccc1',
			'label' => 'Favicon',
			'name' => 'favicon',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => 512,
			'min_height' => 512,
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_574f970dcb7a0',
			'label' => 'ABN',
			'name' => 'abn',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_574f9234ac58f',
			'label' => 'Social Media',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_574f9246ac590',
			'label' => 'Facebook',
			'name' => 'facebook',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array (
			'key' => 'field_574f9257ac591',
			'label' => 'Google Plus',
			'name' => 'google_plus',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array (
			'key' => 'field_574f9260ac592',
			'label' => 'Linked In',
			'name' => 'linked_in',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array (
			'key' => 'field_574f9265ac593',
			'label' => 'Pinterest',
			'name' => 'pinterest',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array (
			'key' => 'field_574f926fac594',
			'label' => 'Twitter',
			'name' => 'twitter',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array (
			'key' => 'field_574f9272ac595',
			'label' => 'Youtube',
			'name' => 'youtube',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array (
			'key' => 'field_574f92b8612de',
			'label' => 'Tracking',
			'name' => '',
			'type' => 'tab',
			'instructions' => 'This is ',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_574f92d5612df',
			'label' => 'Bugherd',
			'name' => 'bugherd',
			'type' => 'textarea',
			'instructions' => 'this is for tracking bugs',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_574f92f3612e0',
			'label' => 'Google Analytics',
			'name' => 'google_analytics',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_574f958cfe018',
			'label' => 'Google Webmaster',
			'name' => 'google_webmaster',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_574f959cfe019',
			'label' => 'Pingdom String',
			'name' => 'pingdom_string',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'b33d48c8d2754bbb90d8b82d19e49af6eb175ae0',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_574f934be1fa2',
			'label' => 'Contact Details',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_574f9371e1fa3',
			'label' => 'Map',
			'name' => 'map',
			'type' => 'google_map',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'center_lat' => '',
			'center_lng' => '',
			'zoom' => '',
			'height' => '',
		),
		array (
			'key' => 'field_5768b3598ded2',
			'label' => 'Phone',
			'name' => 'phone',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_574f937fe1fa4',
			'label' => 'Contact Details',
			'name' => 'contact_details',
			'type' => 'repeater',
			'instructions' => 'tel: and mailto: before a your information makes it open the phone or mail app on phones.
eg tel:000000 or mailto:example@example.com.au',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => '',
			'max' => '',
			'layout' => 'table',
			'button_label' => 'Add Row',
			'sub_fields' => array (
				array (
					'key' => 'field_574f939ce1fa5',
					'label' => 'Label',
					'name' => 'label',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_574f93a3e1fa6',
					'label' => 'Text',
					'name' => 'text',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_574f93a9e1fa7',
					'label' => 'Clickable Text',
					'name' => 'clickable_text',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
			),
		),
		array (
			'key' => 'field_574f94b3cb7f4',
			'label' => 'Default Elements',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_574f94c7cb7f5',
			'label' => 'Default Background Image',
			'name' => 'default_background_image',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'large',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_574f94dbcb7f6',
			'label' => 'Default form',
			'name' => 'default_form',
			'type' => 'gravity_forms_field',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'allow_null' => 0,
			'allow_multiple' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'general-settings',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_5763589a88178',
	'title' => 'Page heading',
	'fields' => array (
		array (
			'key' => 'field_577dde6533e53',
			'label' => 'Background',
			'name' => 'background',
			'type' => 'accordion',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'icon_class' => 'dashicons-arrow-right',
		),
		array (
			'key' => 'field_5763589a8ef79',
			'label' => 'Background',
			'name' => 'background',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_5763589a8ee7d',
			'label' => 'Card',
			'name' => 'card',
			'type' => 'reusable_field_group_field',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'group_key' => 'group_575a26a2487d6',
			'name_prefix' => 0,
			'key_prefix' => 1,
			'label_prefix' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'special',
				'operator' => '==',
				'value' => 'nowhere',
			),
		),
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
			array (
				'param' => 'page_type',
				'operator' => '!=',
				'value' => 'front_page',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_57564e6b9dee8',
	'title' => 'PageBuilder',
	'fields' => array (
		array (
			'key' => 'field_575382e5188eb1',
			'label' => 'Layout',
			'name' => 'layout',
			'type' => 'flexible_content',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'button_label' => 'Add Section',
			'min' => '',
			'max' => '',
			'layouts' => array (
				array (
					'key' => '57563c32414cc',
					'name' => 'section-col-12-floating',
					'label' => 'Background image with floating element',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_5768948f04419',
							'label' => 'Element',
							'name' => 'element',
							'type' => 'reusable_field_group_field',
							'instructions' => '',
							'required' => '',
							'conditional_logic' => '',
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'group_key' => 'group_575a3ce2c0412',
							'name_prefix' => 0,
							'key_prefix' => 1,
							'label_prefix' => 0,
						),
						array (
							'key' => 'field_576b8271cc5fe',
							'label' => 'Advanced Options',
							'name' => 'advanced_options',
							'type' => 'reusable_field_group_field',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'group_key' => 'group_5768d5611288c',
							'name_prefix' => 0,
							'key_prefix' => 1,
							'label_prefix' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '57563ee225179',
					'name' => 'section-col-12-n1',
					'label' => 'One Column',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_576894b6d5800',
							'label' => 'Element',
							'name' => 'element',
							'type' => 'reusable_field_group_field',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'group_key' => 'group_575a4bb07dba7',
							'name_prefix' => 0,
							'key_prefix' => 1,
							'label_prefix' => 0,
						),
						array (
							'key' => 'field_576b8262cc5fd',
							'label' => 'Advanced Options',
							'name' => 'advanced_options',
							'type' => 'reusable_field_group_field',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'group_key' => 'group_5768d5611288c',
							'name_prefix' => 0,
							'key_prefix' => 1,
							'label_prefix' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => 5756433728071,
					'name' => 'section-col-6-n2',
					'label' => 'Two Columns',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_575a3c6680c85',
							'label' => 'Col',
							'name' => 'col',
							'type' => 'column',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'column-type' => '1_2',
						),
						array (
							'key' => 'field_575a4bed93516',
							'label' => 'Element',
							'name' => '1',
							'type' => 'reusable_field_group_field',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'group_key' => 'group_575a3ce2c0412',
							'name_prefix' => 1,
							'key_prefix' => 1,
							'label_prefix' => 0,
						),
						array (
							'key' => 'field_575a3c7480c86',
							'label' => 'Col',
							'name' => 'col',
							'type' => 'column',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'column-type' => '1_2',
						),
						array (
							'key' => 'field_575a4c0193517',
							'label' => 'Element',
							'name' => '2',
							'type' => 'reusable_field_group_field',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'group_key' => 'group_575a3ce2c0412',
							'name_prefix' => 1,
							'key_prefix' => 1,
							'label_prefix' => 0,
						),
						array (
							'key' => 'field_5768d703995fe',
							'label' => 'Advanced Options',
							'name' => 'advanced_options',
							'type' => 'reusable_field_group_field',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'group_key' => 'group_5768d5611288c',
							'name_prefix' => 0,
							'key_prefix' => 1,
							'label_prefix' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '575a49b8fd445',
					'name' => 'section-col-4-n3',
					'label' => 'Three Columns',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_575a4a3afd446',
							'label' => 'Col (copy)',
							'name' => 'col_copy',
							'type' => 'column',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'column-type' => '1_3',
						),
						array (
							'key' => 'field_575a4a42fd447',
							'label' => 'Element',
							'name' => '1',
							'type' => 'reusable_field_group_field',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'group_key' => 'group_575a4bb07dba7',
							'name_prefix' => 1,
							'key_prefix' => 1,
							'label_prefix' => 0,
						),
						array (
							'key' => 'field_575a4a88fd44a',
							'label' => 'Col (copy) (copy)',
							'name' => 'col_copy_copy',
							'type' => 'column',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'column-type' => '1_3',
						),
						array (
							'key' => 'field_575a4a76fd448',
							'label' => 'Element',
							'name' => '2',
							'type' => 'reusable_field_group_field',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'group_key' => 'group_575a4bb07dba7',
							'name_prefix' => 1,
							'key_prefix' => 1,
							'label_prefix' => 0,
						),
						array (
							'key' => 'field_575a4a8cfd44b',
							'label' => 'Col (copy) (copy) (copy)',
							'name' => 'col_copy_copy_copy',
							'type' => 'column',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'column-type' => '1_3',
						),
						array (
							'key' => 'field_575a4a7dfd449',
							'label' => 'Element',
							'name' => '3',
							'type' => 'reusable_field_group_field',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'group_key' => 'group_575a4bb07dba7',
							'name_prefix' => 1,
							'key_prefix' => 1,
							'label_prefix' => 0,
						),
						array (
							'key' => 'field_576b827fcc5ff',
							'label' => 'Advanced Options',
							'name' => 'advanced_options',
							'type' => 'reusable_field_group_field',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'group_key' => 'group_5768d5611288c',
							'name_prefix' => 0,
							'key_prefix' => 1,
							'label_prefix' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '575a4190d0016',
					'name' => 'section-col-3-n4',
					'label' => 'Four Columns',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_575a421ce48fd',
							'label' => 'col',
							'name' => 'col',
							'type' => 'column',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'column-type' => '1_4',
						),
						array (
							'key' => 'field_575a41a5d0017',
							'label' => 'Element',
							'name' => '1',
							'type' => 'reusable_field_group_field',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'group_key' => 'group_575a4bb07dba7',
							'name_prefix' => 1,
							'key_prefix' => 1,
							'label_prefix' => 0,
						),
						array (
							'key' => 'field_575a42d33aa0e',
							'label' => 'col (copy) (copy)',
							'name' => 'col_copy_copy',
							'type' => 'column',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'column-type' => '1_4',
						),
						array (
							'key' => 'field_575a41c8d0019',
							'label' => 'Element',
							'name' => '2',
							'type' => 'reusable_field_group_field',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'group_key' => 'group_575a4bb07dba7',
							'name_prefix' => 1,
							'key_prefix' => 1,
							'label_prefix' => 0,
						),
						array (
							'key' => 'field_575a4250e48fe',
							'label' => 'col (copy)',
							'name' => 'col_copy',
							'type' => 'column',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'column-type' => '1_4',
						),
						array (
							'key' => 'field_575a41d2d001a',
							'label' => 'Element',
							'name' => '3',
							'type' => 'reusable_field_group_field',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'group_key' => 'group_575a4bb07dba7',
							'name_prefix' => 1,
							'key_prefix' => 1,
							'label_prefix' => 0,
						),
						array (
							'key' => 'field_575a4253e48ff',
							'label' => 'col (copy) (copy)',
							'name' => 'col_copy_copy',
							'type' => 'column',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'column-type' => '1_4',
						),
						array (
							'key' => 'field_575a41d9d001b',
							'label' => 'Element',
							'name' => '4',
							'type' => 'reusable_field_group_field',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'group_key' => 'group_575a4bb07dba7',
							'name_prefix' => 1,
							'key_prefix' => 1,
							'label_prefix' => 0,
						),
						array (
							'key' => 'field_57748c3d81371',
							'label' => 'Advanced Options',
							'name' => 'advanced_options',
							'type' => 'reusable_field_group_field',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'group_key' => 'group_5768d5611288c',
							'name_prefix' => 0,
							'key_prefix' => 1,
							'label_prefix' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '575665dbc4a79',
					'name' => 'section-col-12-contact',
					'label' => 'Contact Form Section',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_577de7bb2792a',
							'label' => 'Form',
							'name' => 'form',
							'type' => 'reusable_field_group_field',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'group_key' => 'group_575a30065a430-2',
							'name_prefix' => 0,
							'key_prefix' => 1,
							'label_prefix' => 0,
						),
						array (
							'key' => 'field_57748c4981372',
							'label' => 'Advanced Options',
							'name' => 'advanced_options',
							'type' => 'reusable_field_group_field',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'group_key' => 'group_5768d5611288c',
							'name_prefix' => 0,
							'key_prefix' => 1,
							'label_prefix' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '575612bf9a8f8',
					'name' => 'section-col-12-card',
					'label' => 'Paragraph with Image',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_57845fe114243',
							'label' => 'Card With Image',
							'name' => 'card_with_image',
							'type' => 'reusable_field_group_field',
							'instructions' => '',
							'required' => '',
							'conditional_logic' => '',
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'group_key' => 'group_5768cdd1d2a96',
							'name_prefix' => 1,
							'key_prefix' => 1,
							'label_prefix' => 0,
						),
						array (
							'key' => 'field_576b7fc22a8f8',
							'label' => 'Advanced Options',
							'name' => 'advanced_options',
							'type' => 'reusable_field_group_field',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'group_key' => 'group_5768d5611288c',
							'name_prefix' => 0,
							'key_prefix' => 1,
							'label_prefix' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '575a4d871f595',
					'name' => 'section-col-4-col-8-n2',
					'label' => 'Small Column + Big Column',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_575a4dbf1f596',
							'label' => 'Col',
							'name' => 'col',
							'type' => 'column',
							'instructions' => '',
							'required' => '',
							'conditional_logic' => '',
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'column-type' => '1_4',
						),
						array (
							'key' => 'field_575a4ddf1f598',
							'label' => 'Element',
							'name' => '1',
							'type' => 'reusable_field_group_field',
							'instructions' => '',
							'required' => '',
							'conditional_logic' => '',
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'group_key' => 'group_575a4bb07dba7',
							'name_prefix' => 1,
							'key_prefix' => 1,
							'label_prefix' => 0,
						),
						array (
							'key' => 'field_575a4dd51f597',
							'label' => 'Col (copy)',
							'name' => 'col_copy',
							'type' => 'column',
							'instructions' => '',
							'required' => '',
							'conditional_logic' => '',
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'column-type' => '3_4',
						),
						array (
							'key' => 'field_575a4e001f599',
							'label' => 'Element',
							'name' => '2',
							'type' => 'reusable_field_group_field',
							'instructions' => '',
							'required' => '',
							'conditional_logic' => '',
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'group_key' => 'group_575a4bb07dba7',
							'name_prefix' => 1,
							'key_prefix' => 1,
							'label_prefix' => 0,
						),
						array (
							'key' => 'field_57748c9681373',
							'label' => 'Advanced Options',
							'name' => 'advanced_options',
							'type' => 'reusable_field_group_field',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'group_key' => 'group_5768d5611288c',
							'name_prefix' => 0,
							'key_prefix' => 1,
							'label_prefix' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '575a4e0b1f59a',
					'name' => 'section-col-8-col-4-n2',
					'label' => 'Big Column + Small Column',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_575a4e831f59e',
							'label' => 'Col (copy) (copy)',
							'name' => 'col_copy_copy',
							'type' => 'column',
							'instructions' => '',
							'required' => '',
							'conditional_logic' => '',
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'column-type' => '3_4',
						),
						array (
							'key' => 'field_575a4e3a1f59b',
							'label' => 'Element',
							'name' => '1',
							'type' => 'reusable_field_group_field',
							'instructions' => '',
							'required' => '',
							'conditional_logic' => '',
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'group_key' => 'group_575a4bb07dba7',
							'name_prefix' => 1,
							'key_prefix' => 1,
							'label_prefix' => 0,
						),
						array (
							'key' => 'field_575a4e891f59f',
							'label' => 'Col (copy)',
							'name' => 'col_copy',
							'type' => 'column',
							'instructions' => '',
							'required' => '',
							'conditional_logic' => '',
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'column-type' => '1_4',
						),
						array (
							'key' => 'field_575a4e771f59d',
							'label' => 'Element',
							'name' => '2',
							'type' => 'reusable_field_group_field',
							'instructions' => '',
							'required' => '',
							'conditional_logic' => '',
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'group_key' => 'group_575a4bb07dba7',
							'name_prefix' => 1,
							'key_prefix' => 1,
							'label_prefix' => 0,
						),
						array (
							'key' => 'field_57748cab81374',
							'label' => 'Advanced Options',
							'name' => 'advanced_options',
							'type' => 'reusable_field_group_field',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'group_key' => 'group_5768d5611288c',
							'name_prefix' => 0,
							'key_prefix' => 1,
							'label_prefix' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '575a4ea649724',
					'name' => 'section-col-12-image-grid',
					'label' => 'Image Grid',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_575a4eba49726',
							'label' => 'Card',
							'name' => 'card',
							'type' => 'reusable_field_group_field',
							'instructions' => '',
							'required' => '',
							'conditional_logic' => '',
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'group_key' => 'group_575a26a2487d6',
							'name_prefix' => '',
							'key_prefix' => '',
							'label_prefix' => '',
						),
						array (
							'key' => 'field_575e2b63d03a2',
							'label' => 'Image Grid',
							'name' => 'image_grid',
							'type' => 'reusable_field_group_field',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'group_key' => 'group_575a390f78a8b',
							'name_prefix' => 0,
							'key_prefix' => 1,
							'label_prefix' => 0,
						),
						array (
							'key' => 'field_576b696b82e24',
							'label' => 'Advanced options',
							'name' => 'advanced_options',
							'type' => 'reusable_field_group_field',
							'instructions' => '',
							'required' => '',
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'group_key' => 'group_5768d5611288c',
							'name_prefix' => 0,
							'key_prefix' => 1,
							'label_prefix' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '575a4eec49729',
					'name' => 'section-col-12-slider',
					'label' => 'Slider',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_575f6abfeb104',
							'label' => 'Title Section',
							'name' => 'title',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_575a4f004972a',
							'label' => 'Slider',
							'name' => 'slider',
							'type' => 'reusable_field_group_field',
							'instructions' => '',
							'required' => '',
							'conditional_logic' => '',
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'group_key' => 'group_575a369b061d6',
							'name_prefix' => '',
							'key_prefix' => '',
							'label_prefix' => '',
						),
						array (
							'key' => 'field_576b693382e23',
							'label' => 'advanced_options',
							'name' => 'advanced_options',
							'type' => 'reusable_field_group_field',
							'instructions' => '',
							'required' => '',
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'group_key' => 'group_5768d5611288c',
							'name_prefix' => 0,
							'key_prefix' => 1,
							'label_prefix' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '576c84951046d',
					'name' => 'section-related-items',
					'label' => 'Related Website Items',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_576c84c51046e',
							'label' => 'Website Items',
							'name' => 'website_items',
							'type' => 'relationship',
							'instructions' => '',
							'required' => '',
							'conditional_logic' => '',
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'post_type' => array (
							),
							'taxonomy' => array (
							),
							'filters' => array (
								0 => 'search',
								1 => 'post_type',
							),
							'elements' => array (
								0 => 'featured_image',
							),
							'min' => 1,
							'max' => '',
							'return_format' => 'id',
						),
						array (
							'key' => 'field_576c88b93b350',
							'label' => 'Advanced Options',
							'name' => 'advanced_options',
							'type' => 'reusable_field_group_field',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'group_key' => 'group_5768d5611288c',
							'name_prefix' => 0,
							'key_prefix' => 1,
							'label_prefix' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_575a3ce2c0412',
	'title' => 'Picker - Elements',
	'fields' => array (
		array (
			'key' => 'field_575a3cf5da2e0',
			'label' => 'Element',
			'name' => 'element',
			'type' => 'flexible_content',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'button_label' => 'Add Element',
			'min' => '',
			'max' => '',
			'layouts' => array (
				array (
					'key' => '575a3d0f25fcf',
					'name' => 'card',
					'label' => 'Card',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_57689666d9169',
							'label' => 'card',
							'name' => 'card',
							'type' => 'reusable_field_group_field',
							'instructions' => '',
							'required' => '',
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'group_key' => 'group_575a26a2487d6',
							'name_prefix' => 0,
							'key_prefix' => 1,
							'label_prefix' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '5768ce08aec3f',
					'name' => 'card-img-side',
					'label' => 'Card with side image',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_5768ce08aec40',
							'label' => 'Card with side image',
							'name' => 'card-img-side',
							'type' => 'reusable_field_group_field',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'group_key' => 'group_5768cdd1d2a96',
							'name_prefix' => 0,
							'key_prefix' => 1,
							'label_prefix' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '575a3d79da2e2',
					'name' => 'form',
					'label' => 'Contact Form',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_575a3d83da2e3',
							'label' => 'Form',
							'name' => 'form',
							'type' => 'reusable_field_group_field',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'group_key' => 'group_575a30065a430-2',
							'name_prefix' => 0,
							'key_prefix' => 1,
							'label_prefix' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '575a3e32b3231',
					'name' => 'list',
					'label' => 'List',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_57689683d916b',
							'label' => 'list',
							'name' => 'list',
							'type' => 'reusable_field_group_field',
							'instructions' => '',
							'required' => '',
							'conditional_logic' => '',
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'group_key' => 'group_575a31819691c',
							'name_prefix' => 0,
							'key_prefix' => 1,
							'label_prefix' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '575a3e52b3233',
					'name' => 'slider',
					'label' => 'Slider',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_57689748d916c',
							'label' => 'Slider',
							'name' => 'slider',
							'type' => 'reusable_field_group_field',
							'instructions' => '',
							'required' => '',
							'conditional_logic' => '',
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'group_key' => 'group_575a369b061d6',
							'name_prefix' => 0,
							'key_prefix' => 1,
							'label_prefix' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '575a48e713d73',
					'name' => 'image-grid',
					'label' => 'Image Grid',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_57689764d916d',
							'label' => 'Image Grid',
							'name' => 'image_grid',
							'type' => 'reusable_field_group_field',
							'instructions' => '',
							'required' => '',
							'conditional_logic' => '',
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'group_key' => 'group_575a390f78a8b',
							'name_prefix' => 1,
							'key_prefix' => 1,
							'label_prefix' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '575a495913d75',
					'name' => 'image',
					'label' => 'Image',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_5768977ed916e',
							'label' => 'image',
							'name' => 'image',
							'type' => 'reusable_field_group_field',
							'instructions' => '',
							'required' => '',
							'conditional_logic' => '',
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'group_key' => 'group_575a379a3e69e',
							'name_prefix' => 0,
							'key_prefix' => 1,
							'label_prefix' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '575a497213d77',
					'name' => 'tabs',
					'label' => 'Tabs',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_57689792d916f',
							'label' => 'tabs',
							'name' => 'tabs',
							'type' => 'reusable_field_group_field',
							'instructions' => '',
							'required' => '',
							'conditional_logic' => '',
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'group_key' => 'group_575a3d16b7a47',
							'name_prefix' => 0,
							'key_prefix' => 1,
							'label_prefix' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '5784874bde2c0',
					'name' => 'oembed',
					'label' => 'Media',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_5784876bde2c1',
							'label' => 'Embed Content',
							'name' => 'oembed',
							'type' => 'reusable_field_group_field',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'group_key' => 'group_5784862119b97',
							'name_prefix' => 0,
							'key_prefix' => 1,
							'label_prefix' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'special',
				'operator' => '==',
				'value' => 'nowhere',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_575a4bb07dba7',
	'title' => 'Picker - Elements (Limited 1)',
	'fields' => array (
		array (
			'key' => 'field_575a4bb0b3c46',
			'label' => 'Element',
			'name' => 'element',
			'type' => 'flexible_content',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'button_label' => 'Add Element',
			'min' => 1,
			'max' => 1,
			'layouts' => array (
				array (
					'key' => '575a3d0f25fcf',
					'name' => 'card',
					'label' => 'Card',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_575a4bb0d1d64',
							'label' => 'Card',
							'name' => 'card',
							'type' => 'reusable_field_group_field',
							'instructions' => '',
							'required' => '',
							'conditional_logic' => '',
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'group_key' => 'group_575a26a2487d6',
							'name_prefix' => 0,
							'key_prefix' => 1,
							'label_prefix' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '5768d1d80e515',
					'name' => 'card-img-side',
					'label' => 'Card with Side Image',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_5768d1e70e519',
							'label' => 'Card with Side Image',
							'name' => 'card-img-side',
							'type' => 'reusable_field_group_field',
							'instructions' => '',
							'required' => '',
							'conditional_logic' => '',
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'group_key' => 'group_5768cdd1d2a96',
							'name_prefix' => 0,
							'key_prefix' => 1,
							'label_prefix' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '575a3d79da2e2',
					'name' => 'form',
					'label' => 'Contact Form',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_575a4bb0d1ddb',
							'label' => 'Form',
							'name' => 'form',
							'type' => 'reusable_field_group_field',
							'instructions' => '',
							'required' => '',
							'conditional_logic' => '',
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'group_key' => 'group_575a30065a430-2',
							'name_prefix' => 0,
							'key_prefix' => 1,
							'label_prefix' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '575a3e32b3231',
					'name' => 'list',
					'label' => 'List',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_575a4bb0d1e4b',
							'label' => 'List',
							'name' => 'list',
							'type' => 'reusable_field_group_field',
							'instructions' => '',
							'required' => '',
							'conditional_logic' => '',
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'group_key' => 'group_575a31819691c',
							'name_prefix' => 0,
							'key_prefix' => 1,
							'label_prefix' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '575a3e52b3233',
					'name' => 'slider',
					'label' => 'Slider',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_575a4bb0d1ebf',
							'label' => 'Slider',
							'name' => 'slider',
							'type' => 'reusable_field_group_field',
							'instructions' => '',
							'required' => '',
							'conditional_logic' => '',
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'group_key' => 'group_575a369b061d6',
							'name_prefix' => 0,
							'key_prefix' => 1,
							'label_prefix' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '575a48e713d73',
					'name' => 'image-grid',
					'label' => 'Image Grid',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_575a4bb0d1f30',
							'label' => 'Image Grid',
							'name' => 'image_grid',
							'type' => 'reusable_field_group_field',
							'instructions' => '',
							'required' => '',
							'conditional_logic' => '',
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'group_key' => 'group_575a390f78a8b',
							'name_prefix' => 0,
							'key_prefix' => 1,
							'label_prefix' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '575a495913d75',
					'name' => 'image',
					'label' => 'Image',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_575a4bb0d1fa2',
							'label' => 'Image',
							'name' => 'image',
							'type' => 'reusable_field_group_field',
							'instructions' => '',
							'required' => '',
							'conditional_logic' => '',
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'group_key' => 'group_575a379a3e69e',
							'name_prefix' => 0,
							'key_prefix' => 1,
							'label_prefix' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '575a497213d77',
					'name' => 'tabs',
					'label' => 'Tabs',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_575a4bb0d2014',
							'label' => 'Tabs',
							'name' => 'tabs',
							'type' => 'reusable_field_group_field',
							'instructions' => '',
							'required' => '',
							'conditional_logic' => '',
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'group_key' => 'group_575a3d16b7a47',
							'name_prefix' => 0,
							'key_prefix' => 1,
							'label_prefix' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '57848d78de731',
					'name' => 'oembed',
					'label' => 'Media',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_57848d7ede732',
							'label' => 'oembed',
							'name' => 'oembed',
							'type' => 'reusable_field_group_field',
							'instructions' => '',
							'required' => '',
							'conditional_logic' => '',
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'group_key' => 'group_5784862119b97',
							'name_prefix' => 0,
							'key_prefix' => 1,
							'label_prefix' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'special',
				'operator' => '==',
				'value' => 'nowhere',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_5768d5611288c',
	'title' => 'Section Options - Option',
	'fields' => array (
		array (
			'key' => 'field_577c9ab1e29bf',
			'label' => 'Reset',
			'name' => 'reset',
			'type' => 'column',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'column-type' => '1_1',
		),
		array (
			'key' => 'field_577c98e418d49',
			'label' => 'Section Options',
			'name' => 'section_options',
			'type' => 'accordion',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'icon_class' => 'dashicons-admin-settings',
		),
		array (
			'key' => 'field_5768d5cd60f50',
			'label' => 'Section Width',
			'name' => 'section_width',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'container-fluid' => 'Full screen width',
				'container' => 'Container width',
			),
			'default_value' => array (
				0 => 'container-fluid',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'disabled' => 0,
			'readonly' => 0,
		),
		array (
			'key' => 'field_5768d60a60f51',
			'label' => 'Id',
			'name' => 'id',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '#',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_5779cdd65af53',
			'label' => 'Text Align',
			'name' => 'text_align',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'text-center' => 'Center Text',
				'text-left' => 'Text to the left',
				'text-right' => 'Text to the right',
			),
			'default_value' => array (
				0 => 'text-left',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'disabled' => 0,
			'readonly' => 0,
		),
		array (
			'key' => 'field_5768d65b88866',
			'label' => 'Inside Margin',
			'name' => 'padding',
			'type' => 'select',
			'instructions' => 'this pushes the inside out so it would include the background image and color.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'padding-0' => 'No Inside Margin',
				'padding-4' => '4 Inside Margin',
				'padding-5' => '5 Inside Margin',
				'padding-6' => '6 Inside Margin',
			),
			'default_value' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'disabled' => 0,
			'readonly' => 0,
		),
		array (
			'key' => 'field_5768d68388867',
			'label' => 'Outside Margin',
			'name' => 'margin',
			'type' => 'select',
			'instructions' => 'This pushes the element from the outside and won\'t include background color or images',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'margin-0' => '0 Margin',
				'margin-4' => '4 Margin',
				'margin-5' => '5 Margin',
				'margin-6' => '6 Margin',
			),
			'default_value' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'disabled' => 0,
			'readonly' => 0,
		),
		array (
			'key' => 'field_5779e3d080b7c',
			'label' => 'Border',
			'name' => 'border',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'border-non' => 'No Border',
				'border-top' => 'Top',
				'border-bottom' => 'Bottom',
				'border-left' => 'Left',
				'border-right' => 'Right',
			),
			'default_value' => array (
			),
			'allow_null' => 1,
			'multiple' => 1,
			'ui' => 1,
			'ajax' => 0,
			'placeholder' => '',
			'disabled' => 0,
			'readonly' => 0,
		),
		array (
			'key' => 'field_5768d61360f52',
			'label' => 'Background Color',
			'name' => 'background_color',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'orange-bg' => 'Orange',
				'grey-light-bg' => 'Light Grey',
				'grey-bg' => 'Grey',
				'blue-bg' => 'Blue',
				'white-bg' => 'White',
			),
			'default_value' => array (
				0 => 'white',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'disabled' => 0,
			'readonly' => 0,
		),
		array (
			'key' => 'field_5768dd3c5c1b3',
			'label' => 'Background Image',
			'name' => 'background_image',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'special',
				'operator' => '==',
				'value' => 'nowhere',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_575a369b061d6',
	'title' => 'Slider - Element',
	'fields' => array (
		array (
			'key' => 'field_577ddee91e799',
			'label' => 'Slider',
			'name' => 'slider',
			'type' => 'accordion',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'icon_class' => 'dashicons-slides',
		),
		array (
			'key' => 'field_575a37224f10a',
			'label' => 'Slide Objects',
			'name' => 'slide_objects',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'Website Items' => 'Website Items',
				'Manual' => 'Manual',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => 'Website Items',
			'layout' => 'horizontal',
		),
		array (
			'key' => 'field_575a37644f10b',
			'label' => 'Manual Slider',
			'name' => 'manual_slider',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_575a37224f10a',
						'operator' => '==',
						'value' => 'Manual',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => '',
			'max' => '',
			'layout' => 'block',
			'button_label' => 'Add Slide',
			'sub_fields' => array (
				array (
					'key' => 'field_575a377c4f10c',
					'label' => 'Title',
					'name' => 'title',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_575a369b23c82',
								'operator' => '!=',
								'value' => 'Title',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_575a37834f10d',
					'label' => 'Content',
					'name' => 'content',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_575a369b23c82',
								'operator' => '!=',
								'value' => 'Content',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 1,
				),
				array (
					'key' => 'field_575a37914f10e',
					'label' => 'Image',
					'name' => 'image',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_575a369b23c82',
								'operator' => '!=',
								'value' => 'Image',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'url',
					'preview_size' => 'medium',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
			),
		),
		array (
			'key' => 'field_575a38454f10f',
			'label' => 'Website Items',
			'name' => 'website_items',
			'type' => 'relationship',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_575a37224f10a',
						'operator' => '==',
						'value' => 'Website Items',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array (
			),
			'taxonomy' => array (
			),
			'filters' => array (
				0 => 'search',
				1 => 'post_type',
				2 => 'taxonomy',
			),
			'elements' => array (
				0 => 'featured_image',
			),
			'min' => '',
			'max' => '',
			'return_format' => 'id',
		),
		array (
			'key' => 'field_575a369b23c82',
			'label' => 'Remove Elements',
			'name' => 'remove_elements',
			'type' => 'checkbox',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_575a37224f10a',
						'operator' => '==',
						'value' => 'Manual',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'Title' => 'Title',
				'Content' => 'Content',
				'Image' => 'Image',
			),
			'default_value' => array (
			),
			'layout' => 'horizontal',
			'toggle' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'special',
				'operator' => '==',
				'value' => 'nowhere',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_575a3d16b7a47',
	'title' => 'Tabs - Elements',
	'fields' => array (
		array (
			'key' => 'field_577de5d21a376',
			'label' => 'Tabs',
			'name' => 'tabs',
			'type' => 'accordion',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'icon_class' => 'dashicons-feedback',
		),
		array (
			'key' => 'field_575a3e66b2b24',
			'label' => 'Tab',
			'name' => 'tab',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => '',
			'max' => '',
			'layout' => 'table',
			'button_label' => 'Add Tab',
			'sub_fields' => array (
				array (
					'key' => 'field_575a3d6932723',
					'label' => 'Title',
					'name' => 'title',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_575a3e4db2b23',
					'label' => 'Content',
					'name' => 'content',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 1,
				),
			),
		),
		array (
			'key' => 'field_575a3ec8e7021',
			'label' => 'Type',
			'name' => 'type',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'accordion' => 'Accordion',
				'tab' => 'Tabs',
			),
			'default_value' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'disabled' => 0,
			'readonly' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'special',
				'operator' => '==',
				'value' => 'nowhere',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

endif;

 ?>